// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ??
        const String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:505720774959:android:772a3b34e3118346f801da',
    messagingSenderId: '505720774959',
    projectId: 'faceo-firebase-org',
    storageBucket: 'faceo-firebase-org.firebasestorage.app',
  );

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ??
        dotenv.env['FIREBASE_ANDROID_API_KEY'] ??
        const String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:505720774959:web:772a3b34e3118346f801da',
    messagingSenderId: '505720774959',
    projectId: 'faceo-firebase-org',
    storageBucket: 'faceo-firebase-org.firebasestorage.app',
    authDomain: 'faceo-firebase-org.firebaseapp.com',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ??
        const String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:505720774959:ios:65c8028c2fe06428f801da',
    messagingSenderId: '505720774959',
    projectId: 'faceo-firebase-org',
    storageBucket: 'faceo-firebase-org.firebasestorage.app',
    iosBundleId: 'com.example.faceo',
  );
}

